/* AUTO-GENERATED from packages/astro/src/packs/woo/components/FitRecommender. Edit there, then run: npm --prefix packages/astro run gen */
/* Generated by packages/astro/scripts/gen-bundles.mjs — do not edit. */
"use strict";
var __dsgo_woo_fit_recommender = (() => {
  var __defProp = Object.defineProperty;
  var __getOwnPropDesc = Object.getOwnPropertyDescriptor;
  var __getOwnPropNames = Object.getOwnPropertyNames;
  var __hasOwnProp = Object.prototype.hasOwnProperty;
  var __export = (target, all) => {
    for (var name in all)
      __defProp(target, name, { get: all[name], enumerable: true });
  };
  var __copyProps = (to, from, except, desc) => {
    if (from && typeof from === "object" || typeof from === "function") {
      for (let key of __getOwnPropNames(from))
        if (!__hasOwnProp.call(to, key) && key !== except)
          __defProp(to, key, { get: () => from[key], enumerable: !(desc = __getOwnPropDesc(from, key)) || desc.enumerable });
    }
    return to;
  };
  var __toCommonJS = (mod) => __copyProps(__defProp({}, "__esModule", { value: true }), mod);

  // src/packs/woo/components/FitRecommender/FitRecommender.client.ts
  var FitRecommender_client_exports = {};
  __export(FitRecommender_client_exports, {
    mount: () => mount
  });

  // src/_shared/bridge.ts
  function bridge() {
    const b = typeof window !== "undefined" ? window.dsgo : void 0;
    if (!b) {
      throw new Error(
        "dsgo bridge not available. This component must run on a DesignSetGo Apps page (the Astro site itself must be deployed as a DSGo app, OR the page must be served by the DSGo inline-mode loader)."
      );
    }
    return b;
  }
  async function ready() {
    return bridge().ready;
  }
  function commerce() {
    return bridge().commerce;
  }
  function storage() {
    return bridge().storage;
  }

  // src/_shared/dom.ts
  function $$(root, selector) {
    return Array.from(root.querySelectorAll(selector));
  }
  function bind(root, key) {
    return root.querySelector(`[data-bind="${cssEscape(key)}"]`);
  }
  function cssEscape(s) {
    if (typeof CSS !== "undefined" && typeof CSS.escape === "function") return CSS.escape(s);
    return s.replace(/[^a-zA-Z0-9_-]/g, (c) => `\\${c.codePointAt(0).toString(16)} `);
  }

  // src/packs/woo/components/FitRecommender/FitRecommender.client.ts
  var STRINGS = {
    heading: "Find your size",
    intro: "Three quick questions. We'll remember the answers across products.",
    height_label: "Your height",
    build_label: "Your build",
    build_slim: "Slim",
    build_regular: "Regular",
    build_athletic: "Athletic",
    fit_label: "How do you like clothes to fit?",
    fit_snug: "Snug",
    fit_true: "True",
    fit_relaxed: "Relaxed",
    submit: "Get my size",
    result_label: "Recommended for this product",
    caveat: "Recommendation only. Check the size guide for measurements.",
    retake: "Retake quiz",
    no_sizes: "This product doesn't have a size attribute, so we can't recommend a fit."
  };
  var t = (key) => STRINGS[key];
  var STORAGE_KEY = "fit.answers";
  function bindStrings(root) {
    for (const node of $$(root, "[data-bind]")) {
      const key = node.getAttribute("data-bind");
      if (key && key in STRINGS && node.children.length === 0) {
        node.textContent = t(key);
      }
    }
  }
  function productIdFromContext() {
    var _a, _b, _c, _d, _e;
    const w = typeof window !== "undefined" ? window : void 0;
    const props = (_b = (_a = w == null ? void 0 : w.dsgo) == null ? void 0 : _a.context) == null ? void 0 : _b.blockProps;
    if (props == null ? void 0 : props.product_id) return Number(props.product_id);
    const qs = new URLSearchParams((_e = (_d = (_c = w == null ? void 0 : w.dsgo) == null ? void 0 : _c.context) == null ? void 0 : _d.search) != null ? _e : "");
    const id = qs.get("product_id") || qs.get("pid");
    return id ? Number(id) : null;
  }
  async function fetchSizeTerms(productId) {
    var _a, _b;
    if (!productId) return [];
    try {
      const p = await commerce().products.get(productId);
      const sizeAttr = ((_a = p == null ? void 0 : p.attributes) != null ? _a : []).find((a) => /size/i.test(a.name));
      return ((_b = sizeAttr == null ? void 0 : sizeAttr.terms) != null ? _b : []).map((t2) => t2.name).filter(Boolean);
    } catch {
      return [];
    }
  }
  function pickIndex(answers, n) {
    var _a, _b, _c;
    if (n <= 1) return 0;
    let score = 0;
    score += (_a = { short: 0, medium: 1, tall: 2 }[answers.height]) != null ? _a : 1;
    score += (_b = { slim: 0, regular: 1, athletic: 2 }[answers.build]) != null ? _b : 1;
    score += (_c = { snug: -1, true: 0, relaxed: 1 }[answers.fit]) != null ? _c : 0;
    score = Math.max(0, Math.min(6, score));
    const ratio = score / 6;
    return Math.round(ratio * (n - 1));
  }
  function showResult(root, answers, terms) {
    var _a;
    const formEl = bind(root, "form");
    const resultEl = bind(root, "result");
    const noSizesEl = bind(root, "no_sizes");
    const sizeEl = bind(root, "size");
    if (!terms.length) {
      if (formEl) formEl.hidden = true;
      if (noSizesEl) noSizesEl.hidden = false;
      return;
    }
    const idx = pickIndex(answers, terms.length);
    if (sizeEl) sizeEl.textContent = (_a = terms[idx]) != null ? _a : null;
    if (formEl) formEl.hidden = true;
    if (resultEl) resultEl.hidden = false;
  }
  async function mount(root, _props) {
    await ready();
    bindStrings(root);
    const productId = productIdFromContext();
    const terms = await fetchSizeTerms(productId);
    let savedAnswers = null;
    try {
      const saved = await storage().user.get(STORAGE_KEY);
      if (saved && typeof saved === "object" && !Array.isArray(saved)) {
        savedAnswers = saved;
      }
    } catch {
    }
    if (savedAnswers) {
      showResult(root, savedAnswers, terms);
    }
    const formEl = bind(root, "form");
    const resultEl = bind(root, "result");
    const retakeEl = bind(root, "retake");
    formEl == null ? void 0 : formEl.addEventListener("submit", async (event) => {
      var _a, _b, _c;
      event.preventDefault();
      const data = new FormData(event.currentTarget);
      const answers = {
        height: (_a = data.get("height")) != null ? _a : "",
        build: (_b = data.get("build")) != null ? _b : "",
        fit: (_c = data.get("fit")) != null ? _c : ""
      };
      try {
        await storage().user.set(STORAGE_KEY, answers);
      } catch {
      }
      showResult(root, answers, terms);
    });
    retakeEl == null ? void 0 : retakeEl.addEventListener("click", async () => {
      try {
        await storage().user.set(STORAGE_KEY, null);
      } catch {
      }
      if (resultEl) resultEl.hidden = true;
      if (formEl) {
        formEl.hidden = false;
        formEl.reset();
      }
    });
  }
  return __toCommonJS(FitRecommender_client_exports);
})();

;(function(){
  var __dsgo_mount = __dsgo_woo_fit_recommender.mount;
  function mountAll(){
    document.querySelectorAll('[data-dsgo-component="woo-fit-recommender"]').forEach(function(root){
      if(root.dataset.dsgoMounted === '1') return;
      root.dataset.dsgoMounted = '1';
      var props;
      try { props = JSON.parse(root.dataset.dsgoProps || '{}'); }
      catch(e){ console.error('[dsgo] invalid data-dsgo-props on', root, e); return; }
      __dsgo_mount(root, props);
    });
  }
  if(document.readyState === 'loading'){
    document.addEventListener('DOMContentLoaded', mountAll, { once: true });
  } else { mountAll(); }
})();

